apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    service: client
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      service: client
  template:
    metadata:
      labels:
        service: client
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.app.pullSecret }}
      containers:
        - name: client
          image: "{{ .Values.image.app.url }}:{{ .Values.image.app.tag }}"
          imagePullPolicy: {{ .Values.image.app.pullPolicy }}
          ports:
            - containerPort: {{ .Values.port }}
          env:
            - name: current_network
              value: {{ .Values.env.current_network | quote }}
            - name: token_contract
              value: {{ .Values.env.token_contract | quote }}
            - name: proxy_contract
              value: {{ .Values.env.proxy_contract | quote }}
            - name: zrc1_contract
              value: {{ .Values.env.zrc1_contract | quote }}
            - name: zrc6_contract
              value: {{ .Values.env.zrc6_contract | quote }}
            - name: migrator_contract
              value: {{ .Values.env.migrator_contract | quote }}
            - name: rewards_contract
              value: {{ .Values.env.rewards_contract | quote }}
            - name: voucher_contract
              value: {{ .Values.env.voucher_contract | quote }}
            - name: ownership_contract
              value: {{ .Values.env.ownership_contract | quote }}

          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
